### ISSUE TITLE
[FEATURE] Créer une vue pour revalider les habilitations

### ISSUE THREAD

**Issue by cverons** [GDI-NC/ADESS-App-Issues#12]
Ajouter une vue dans l'interface utilisateur pour permettre la revalidation des habilitations.

Il devra être possible de revalider ou de supprimer plusieurs habilitations simultanément.

**Comment by fdanielsfc** [comment]
Bonjour,

1) Ajout d’une configuration générale dans paramètres, Option On/Off pour activer ou désactiver la gestion de la revalidation : OK

2) Pour chaque type de ressource : 
- Définition d’une durée de validation des habilitations avant revalidation.
- Définition d’un delai de revalidation avant expiration.
- Choix d’une action en cas de dépassement du delai (désactivation de l’habilitation, ou aucune action).

=> Dans l'interface à la definition par type de ressource les libellés ne sont pas clairs.
Il serait intéressant de modifier :
Durée = "Validité maximale des habilitations"
Delai = "Periode de revalidation des habilitations"
 Action = "Activation de la revalidation" (avec les valeurs oui ou non)
![image](https://user-images.githubusercontent.com/89943417/141387685-e7d66c86-a21f-4c9b-8808-5308e10cc3c4.png)

              
3)  Un nouveau menu dans l’onglet Habilitations « Revalidations » permet d’afficher toutes les habilitations gérées par l’utilisateur / administrateur connecté au GDI.
  L’utilisateur pouvant alors sélectionner les habilitations et les revalider ou supprimer. (ou bouton supplémentaire permettra de tout cocher d’un coup)
![image](https://user-images.githubusercontent.com/89943417/141388296-8056f6b1-7679-4186-8873-3be5fc784ad6.png)

=> Nécessite de pouvoir redimensionner les colonnes (surtout le nom de la ressource)
Je n'ai pas vérifié, mais évidemment la revalidation doit modifier la date de modification et le modificateur de l'habilitation.
Et ne proposer que les habilitations sur lesquelles l'utilisateur connécté au GDI a les droits. (delegation sur la ressource associée a l'habilitation)


Au niveau du fonctionnement je voit qu'il y a eu une incompréhension. Mais je vais voir avec le client si cela lui convient, je pense que cela devrai répondre au besoin.
Pour que cela réponde au besoin il faudrait par contre que si l'option de revalidation est activée au niveau de l'application et au niveau du type de ressource, que toutes les habilitations soient créées par défaut avec une date de fin = date du jour + durée correspondante a la ressource.
![image](https://user-images.githubusercontent.com/89943417/141390953-7b0813ec-4fb1-4f78-bbf3-a43b881611a9.png)
L'utilisateur pouvant alors définir une date de fin plus courte, mais pas plus loin que la date de fin par défaut. (cela permet d'obliger les utilisateurs a revalider les habilitations a minima tous les x jours, par exemple tous les ans)

**Comment by jchable** [comment]
Selon mail de @fdanielsfc, nécessite quelques ajustements.

**Comment by fdanielsfc** [comment]
Je vient de tester les fonctionnalités.

1) Modification des libellés : OK
2) Redimension des colonnes : OK
3) Définition des dates de fin : 
- Les habilitations soient créées par défaut avec une date de fin = date du jour + durée correspondante a la ressource : OK
- L'utilisateur pouvant alors définir une date de fin plus courte, mais pas plus loin que la date de fin par défaut : Ne fonctionne pas, il est possible de définir une date plus loin dans le futur que la durée.
<img width="233" alt="02" src="https://user-images.githubusercontent.com/89943417/142963137-a0e8cbce-03e9-4661-8f22-5264f68bea3b.PNG">
<img width="904" alt="03" src="https://user-images.githubusercontent.com/89943417/142963140-0a2e54b9-8fa6-4993-a10f-1249eb4f58a3.PNG">

5) A la revalidation d'une habilitation, modifier la date de fin = date du jour + durée correspondante a la ressource.
=> Actuellement ajoute la durée a la date de fin existante. Si la date est dépassée depuis longtemps, la date peut rester depassée. Et cela ne permet pas de caler toutes les dates de revalidations a la meme date. A la revalidation il faudrait définir  date de fin = date du jour + durée correspondante a la ressource.
<img width="912" alt="04" src="https://user-images.githubusercontent.com/89943417/142963282-f6f3784c-7284-4d78-a51e-af025a7294fa.PNG">
<img width="906" alt="05" src="https://user-images.githubusercontent.com/89943417/142963289-bd388c03-ba41-4fa3-9fa4-944bfc1d1cc7.PNG">

Et petite question, a quoi correspond ce rond qui apparait sur la configuration des ressources ? (ca n'a pas l'air de correspondre a l'option de rehabilitation)
<img width="904" alt="01" src="https://user-images.githubusercontent.com/89943417/142963014-35890210-eb81-4fd4-a2d2-4844176cb712.PNG">
