### ISSUE TITLE
[FEATURE] Permettre la creation de niveaux d'organisation racine supplémentaires depuis l’interface.

### ISSUE THREAD

**Issue by jchable** [GDI-NC/ADESS-App-Issues#13]
Besoin remonté par Fred => permettre la creation de niveaux d'organisation racine supplémentaires depuis l’interface. 
A évaluer sur la faisabilité.

**Comment by cverons** [comment]
Afin de permettre aux utilisateurs de supprimer les niveaux d'organisation de la corbeille, les délégations ne sont plus supprimées lorsque le niveau d'organisation est déplacé vers la corbeille, mais lorsqu'il est supprimé définitivement.
