### ISSUE TITLE
[FEATURE] Champs téléphones

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#19]
Les champs téléphone sont limités en dur a 6 chiffres dans l’interface.
Ceci correspond à une réalité en Calédonie mais va poser soucis à l’exportation.
Il faudrait permettre la saisie de plus de chiffres.
![Picture1](https://user-images.githubusercontent.com/89943417/138773221-8586b808-91f2-4cf2-ab96-2c0de61fd789.png)

**Comment by jchable** [comment]
@fdanielsfc Doublon avec le ticket #61 . Tu confirmes ?

**Comment by fdanielsfc** [comment]
Oui c'est bien la meme chose. Permettre la saisie d'un nombre libre de chiffre, avec le controle uniquement par regex.

**Comment by jchable** [comment]
Du coup @fdanielsfc , c'est un doublon et nous pouvons cloturer celle-ci puisque l'autre a été traité.

**Comment by jchable** [comment]
@cverons est-ce que l'on est capable de changer dans la configuration de l'application le nombre de chiffres ? Ou mieux un champ texte avec règle REGEXP pour être plus flexible et certainement moins chronophage à faire ?

**Comment by jchable** [comment]
Nécessaire pour le déploiement à la Réunion en semaine du 20/03.
