### ISSUE TITLE
[FEATURE] Affectation d'habilitations multiple

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#25]
Lors de l’affectation de nouvelles habilitations sur une fiche utilisateur, avant on pouvait sélectionner plusieurs ressources en une seule fois.
Aujourd’hui il faut les ajouter une par une ce qui n'est pas pratique.
Il faudrait prevoir de permettre une selection multiple :
Plusieurs habilitations pour un utilisateurs, et plusieurs utilisateurs pour une habilitation

**Comment by fdanielsfc** [comment]
![image](https://user-images.githubusercontent.com/89943417/141004429-509f7160-f5ce-4f10-b2da-434b609b234a.png)

![image](https://user-images.githubusercontent.com/89943417/141004439-3a3482a7-1ff1-44bc-a9f4-7da76538e78a.png)

Très pénalisant car engendre une grosse perte de temps pour les clients (remonté comme une regression par la Mairie).

**Comment by jchable** [comment]
Selon @fdanielsfc => #25 : Affectation d’habilitations multiples. Possible sur l’ancienne version, ils ne considèrent donc pas cela comme une evolution mais comme une regression bloquante.

**Comment by cverons** [comment]
Je viens d'intégrer la possibilité de **créer** une habilitation pour plusieurs ressources simultanément.
_Note : Il n'est pas possible de modifier plusieurs habilitations de cette façon._

La copie écran ci-dessous montre un exemple d'utilisation du nouveau formulaire :

![image](https://user-images.githubusercontent.com/20375763/154422354-42347869-7c95-45fc-a37e-107a6f7e49ad.png)

Il est à noter que la création tient compte des **demandes** si l'utilisateur ne possède pas les délégations suffisantes sur le niveau d'organisation des ressources sélectionnées.
Les ressources faisant l'objet d'une demande sont identifiées par une icône de demande.
