### ISSUE TITLE
[FEATURE] Photo par défaut

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#31]
Permettre l'affichage d'une photo par defaut au lieu du texte
![Capture](https://user-images.githubusercontent.com/89943417/138775442-2df38f04-bcc8-4f8e-a739-abf2dacc97d4.PNG)

Par exemple comme dans la v3 :
![Capture](https://user-images.githubusercontent.com/89943417/138775542-7785a75a-2452-4cae-a619-2c1ab74d9140.PNG)

**Comment by cverons** [comment]
La photo par défaut doit se nommer `default_user.png` et se trouver dans le répertoire `photos` de l'application.

**Comment by jchable** [comment]
@fdanielsfc est-ce que cela clôt le ticket de ton côté ?

**Comment by fdanielsfc** [comment]
yes, merci.
