### ISSUE TITLE
[BUG] Affichage / tri des habilitations

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#38]
GDI v4.0.9, Sur tous les navigateurs

Le tri des habilitations ce fait mal.
1er affichage par défaut depuis les habilitations d'un utilisateur :
![image](https://user-images.githubusercontent.com/89943417/141001427-54da02a3-4dba-42ce-a2e6-7fa5347335ac.png)

Si on clique une 1ère fois sur « Ressource » : un « cta » s’intercale… puis on retrouve du DSIS\03 alors que juste avant on avait du DSIS\05 :
![image](https://user-images.githubusercontent.com/89943417/141001456-35ff2828-6c4d-4fd5-9574-62c388944ed7.png)

Si on clique une 2e fois :
![image](https://user-images.githubusercontent.com/89943417/141001481-7f4af79a-d4af-42ca-9d76-7dfa56d4ddbe.png)
![image](https://user-images.githubusercontent.com/89943417/141001493-f436853c-470a-4857-935f-c23fbbb08792.png)

Il faudrait que les habilitations puissent etre triées par ordre alphabetique des ressources pour permettre aux utilisateurs de s'y retrouver.

**Comment by cverons** [comment]
La colonne "Affichage" des ressources est une donnée calculée, il n'est donc pas possible de trier sur cette information côté base de données.
J'ai capturé l'événement du tri de la grille pour décomposer la requête afin d'obtenir le résultat attendu.
