### ISSUE TITLE
[BUG] Affichage des n° des ressources

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#45]
**Version de l'application concernée**
GDI v4.0.9, Sur tous les navigateurs

**Décrire l'incident**
Le n° des ressources s’affichais dans l'affichage des ressources et ne ‘affiche plus dans la nouvelle interface.
TRES pénalisant pour le suivi des ressources.
![image](https://user-images.githubusercontent.com/89943417/141024793-5525d57b-6b8f-4c6a-8ae0-7107f41457f8.png)

**Comment by jchable** [comment]
Selon @fdanielsfc => : Affichage des n° de ressources. Critique car ils verifient le RessourceID pour verifier si le droit est bien appliqué pour l'utilisateur dans l’AD. Il ne s'agit pas d'une évolution: déjà disponible sur la version actuelle en prod
