### ISSUE TITLE
[BUG] Impossible d'ajouter des habilitations sur une ressource enfant d'une ressource héritée

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#46]
**Version de l'application concernée**
4.0.9

**Décrire l'incident**
Impossible d'ajouter des habilitations sur une ressource enfant d'une ressource héritée.

**Comment le reproduire ?**
Une ressource fichier est configurée avec l'heritage (donc impossible d'y associer des habilitations, comme prévu)
<img width="472" alt="01" src="https://user-images.githubusercontent.com/89943417/142945425-9acc13c5-21e1-4741-b659-c6076733ae1c.PNG">

Une ressource enfant sans héritage.
<img width="461" alt="02" src="https://user-images.githubusercontent.com/89943417/142945448-3723ef82-06ae-4cf2-ab6f-bc49aa0e7672.PNG">

Quand on veut ajouter une habilitation ces ressources ne sont pas proposées. (aussi bien celle avec heritage que celle sans)
Celle sans heritage devrai pouvoir etre selectionnée.
<img width="424" alt="04" src="https://user-images.githubusercontent.com/89943417/142945532-b859710c-a6b5-4b48-9841-71ca0c8b4830.PNG">

**Ordinateur de bureau (veuillez compléter les informations suivantes) :**
 - Navigateur Chrome 96.0.4664.45

**Comment by cverons** [comment]
Les ressources qui héritent des habilitations de leur parent apparaissent dans le menu déroulant avec une couleur plus claire afin de les distinguer.
![image](https://user-images.githubusercontent.com/20375763/148857457-b2306707-1b63-497a-a8d8-96a5c637189b.png)
Elles ne sont sélectionnables.
Si elles ont des enfants, cliquer dessus ouvre ou ferme les nœuds enfants.
Les enfants qui n'ont pas d'héritage peuvent recevoir des habilitations.
