### ISSUE TITLE
[BUG] Recuperation des membres d'un role par l'API

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#47]
**Version de l'application concernée**
4.0.9

**Décrire l'incident**
Soucis pour récupérer les membres d'un role par l'API.

**Comment le reproduire ?**
L'appel de l'API Role\AvailableUsers(RoleID) renvoit la liste de tous les utilisateurs du GDI et non pas ceux membres du role.
De meme pour utilisateurs\AvailableRoles(UtilisateurID) renvoit la liste de tous les roles.
Comment peut on sortir la liste de tous les membres d'un role par les API existantes ?
![image](https://user-images.githubusercontent.com/89943417/143119263-5aeb667f-2063-40f1-8151-30527c6a7ae8.png)

**Comment by jchable** [comment]
@cverons si tu as une réponse, tag moi dans la carte que je l'ajoute à la documentation des APIs, thanks.

**Comment by cverons** [comment]
Voici le endpoint pour obtenir la liste des membres d'un rôle `<url>/odata/<version>/roles/members(<roleId>)` où :
- `<url>` est l'url du serveur api
- `<version>` est la version de l'api
- `<roleId>` est l'identifiant du rôle dont on veut les membres

Pour obtenir la liste liste des rôles d'un utilisateur : `<url>/odata/<version>/utilisateurs(<userId>)?$expand=roles`
