### ISSUE TITLE
[FEATURE] Gestion des champs custom par les API

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#5]
**Décrire l'incident**
Pas de gestion des champs custom par les API

**Quel est le comportement attendu ?**
Afin de ne plus appeler en direct la base de donnée il faut que tous les champs soient modifiables par les API.

**Comment by cverons** [comment]
Les champs `custom` sont propres aux scripts.
Il n'est pas cohérent de polluer l'API et la base de données avec ce type d'information.

**Comment by fdanielsfc** [comment]
Cela est ton point de vue, mais pour avoir une cohérence général de l'application il faudrait que tout soit géré de la meme maniere par les API.
Sans cela je devrai continuer a taper la base de donnée en direct ce qui, je te l'accorde, n'est pas idéal.
Merci donc de prendre en compte ces contraintes fonctionnelles.

**Comment by jchable** [comment]
@fdanielsfc est-ce une fonctionnalité ? A quoi servent les champs customs en bdd ? Es-ce que c'est un besoin client / métier et donc une fonctionnalité pour nous à intégrer ?

**Comment by fdanielsfc** [comment]
Ces champs libres n'apparaissent pas dans l'interface (pas pour le moment du moins) mais servent à stocker des données récupérées / calculées depuis d'autres annuaires.
Les données stockées servent ensuite dans les automatisations pour les clients.
Par exemple pour la SGCB on a un custom qui sert a definir les comptes devant avoir un acces telephonique a l'international, et un custom activant la synchronisation des email vers le groupe en france.
Donc oui cela repond a des besoins precis que l'application generique ne peut pas prendre en compte.

**Comment by jchable** [comment]
@cverons Ca me semble être une fonctionnalité intéressante (à laquelle j'avais déjà songé pour les intégrations métier) voire indispensable. Qu'en penses-tu ?

**Comment by cverons** [comment]
Les colonnes `CustomAttribute1`, `CustomAttribute2` et `CustomAttribute3` sont désormais mises à jour via l'API pour les tables suivantes :

- Fonction
- Habilitation
- Niveau d'organisation
- Ressource
