### ISSUE TITLE
[BUG] Impossibilité de visualiser les ressources racines

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#50]
**Version de l'application concernée**
4.10

**Décrire l'incident**
L'interface ne permet pas de visualiser les ressources racines.
Celles ci ne doivent pas etre modifiables , mais le manque d'affichage empeche de visualiser les habilitations associées, et d'executer la generation du rapport d'audit.

![test - 31](https://user-images.githubusercontent.com/89943417/144521153-8a88bf10-b987-49d6-819c-f5b7f1fdd0d1.PNG)

![test - 3](https://user-images.githubusercontent.com/89943417/144521179-9673578a-3316-4f2d-8373-5c31aa33e708.PNG)

**Comment by jchable** [comment]
@cverons Le problème est que vu que l'on ne peut pas modifier la ressource, on ne peut pas voir les habilitations. Permettra de visualiser les habilitations des niveaux racines comme pour les autres ressources (mais en empêchant la modification de la ressource)

**Comment by cverons** [comment]
Revu entièrement avec la v5
