### ISSUE TITLE
[BUG] Affichage a la creation d'utilisateur 

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#52]
**Version de l'application concernée**
4.10

**Décrire l'incident**
Dans un GDI ayant plusieurs niveaux racines, a la creation d'un utilisateur n'affiche pas le formulaire par defaut.
![test - 2](https://user-images.githubusercontent.com/89943417/144521561-370eac34-8e58-4e9b-a596-aa727e776916.PNG)

Il faut cliquer sur "Fiche Utilisateur" pour ouvrir la fiche. Celle ci devrai apparaitre par défaut.

**Ordinateur de bureau (veuillez compléter les informations suivantes) :**
Navigateur Chrome 96.0.4664

**Comment by cverons** [comment]
Impossible de reproduire ce cas sur la v4.1.0, merci de fournir plus d'information aidant à sa reproduction.

**Comment by alanmallegol** [comment]
Doublon du #86
