### ISSUE TITLE
[BUG] Creation de niveaux d'organisation

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#53]
**Version de l'application concernée**
4.0.9

**Décrire l'incident**
Impossibilité de créer un niveau d'organisation par l'interface.
Le bouton enregistrer n'as pas d'effet, aucun message n'apparait.

**Comment le reproduire ?**
Creation d'un niveau d'organisation, clic sur le bouton enregistrer ne produit aucun effet.
![test1](https://user-images.githubusercontent.com/89943417/144922556-06d7be6a-d267-4689-b16d-4cdf27425b5d.PNG)

Le debug n'affiche rien non plus.
![test3](https://user-images.githubusercontent.com/89943417/144922954-c2ec16f2-418d-407d-a3b9-832c7bf84c19.PNG)

**Smartphone (veuillez compléter les informations suivantes) :**
Navigateur Firefox ou Edge

**Comment by cverons** [comment]
Pas reproduit sur la v4.1.0, attention aux délégations nécessaires en cas de création d'un noeud enfant.
