### ISSUE TITLE
[BUG] Navigation lors de la creation d'habilitations d'organisation

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#60]
**Version de l'application concernée**
4.0.9.

**Décrire l'incident**
Apres création d’habilitation on revient sur le niveau par défaut et non le niveau d’origine.

**Comment le reproduire ?**
Depuis le détail de l’organisation, choix du niveau et clic sur nouvelle habilitation.
![image](https://user-images.githubusercontent.com/89943417/146881409-eaba1fc2-7332-4aeb-9f54-1885f15867cd.png)

Apres création de l’habilitation on revient alors sur le niveau par défaut et non le niveau d’origine (ici production).
Ceci est pénalisant quand on souhaite ajouter plusieurs habilitations pour un niveau d’organisation (qu’il faut alors resélectionner a chaque fois)
![image](https://user-images.githubusercontent.com/89943417/146881490-966786a9-e8b9-425d-939e-8ca6665b9a6a.png)
![image](https://user-images.githubusercontent.com/89943417/146881498-d5f4afc0-7199-4cfe-94f6-484b1177f5ca.png)

**Comment by jchable** [comment]
@fdanielsfc quand tu parles de niveau, c'est en fait le filtre Production/T2S ? En gros, il faut qu'au retour de la création de la nouvelle habilitation, tu es le même écran + la nouvelle habilitation d'affichée si correspond au filtre ?

**Comment by fdanielsfc** [comment]
tout a fait, qu'a l'enregistrement de l'habilitation on revienne sur l'ecran précédent.

**Comment by cverons** [comment]
Le niveau d'organisation sélectionné est sauvegardé dans la session de l'utilisateur.
