### ISSUE TITLE
[BUG] Regle regex sur le nom

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#63]
**Version de l'application concernée**
Version 4.09

**Décrire l'incident**
La regle regex ne semble pas correctement appliquée dans l'interface.

**Comment le reproduire ?**
Définition de la regle regex et test avec le nom de l'utilisateur (ok)
![GDI01](https://user-images.githubusercontent.com/89943417/155981755-52e219dc-2037-4694-9acb-31d35542dec1.PNG)

Tentative de modification de l'utilisateur en erreur, car ne correspondant apparement pas a la regle regex.
![GDI02](https://user-images.githubusercontent.com/89943417/155981868-fc06744c-65e8-4c6d-99c9-ceedccf9ccc4.PNG)

**Comment by fdanielsfc** [comment]
Sous Firefox 78.13

**Comment by jchable** [comment]
@cverons Pour ce ticket, juste intégrer le '-' dans la regexp. A priori la règle regexp modifiée n'est pas prise en compte.

**Comment by cverons** [comment]
Pas de problème avec la 4.1
