### ISSUE TITLE
[BUG] Calcul du login utilisateur

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#74]
**Version de l'application concernée**
V4.1.1

**Décrire l'incident**
A la création d'un utilisateur le login n'est plus calculé automatiquement.
![image](https://user-images.githubusercontent.com/89943417/166327038-4b481edd-7d7c-473c-b370-9bb3aa8ee37a.png)

**Comment by cverons** [comment]
La règle de génération du `Login` s'applique :
- Lorsque le formulaire est en mode Création
- Lorsque le `Type d'utilisateur` est renseigné
- Lorsque le `Nom` est renseigné
- Lorsque le `Prénom` est renseigné
