### ISSUE TITLE
[BUG] Bouton Eclair

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/ADESS-App-Issues#75]
**Version de l'application concernée**
V4.1.1

**Décrire l'incident**
Appuie sur l’éclair pour un utilisateur échoue et renvoi l’erreur suivante.
En base le champ updated n’est pas changé.
![image](https://user-images.githubusercontent.com/89943417/166327181-254d5f44-7185-42cf-97e8-e64baa4c903d.png)

Fonctionne correctement pour les niveaux et ressources.

**Comment by cverons** [comment]
Cette fonctionnalité est correcte, vérifier que cet utilisateur ne possède pas plusieurs habilitations actives pour la même ressource.
